 const PRODUCTS = ['Bar Soap',
 'Liquid Soap',
 'Shampoo',
 'Conditioner',
 'Body Wash',
 'Floss',
 'Toothbrush',
 'Toothpaste',
 'Deodorant',
 'Shaving Cream',
 'Hair Moisturizer',
 'Hair Oil',
 'Sponge',
 'Dish soap',
 'Disinfectant wipes',
 'Hand Sanitizer',
 'Lotion',
 'Band aids',
 'Lip Balm',
 'Pads',
 'Tampons',
 'Baby wipes',
 'Diaper Rash cream',
 'Diapers',
 'Toilet Paper',
 'Paper Towels',
 'Facial Tissue']